name: SonarQube Analysis

on:
  push:
    branches-ignore:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'  # Tüm branch'lerde çalışacak şekilde ayarlandı
  schedule:
    - cron: '0 0 * * *'  # Günlük olarak saat 00:00 UTC'de çalışacak (isteğe bağlı, kaldırabilirsiniz)

jobs:
  sonarqube_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '4.x'  # Node.js 4.x sürümünü kullanacak şekilde ayarlandı

      - name: Install dependencies
        run: npm install  # Projeye bağlı olarak gerekirse değiştirilebilir

      - name: Run SonarQube Scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SonarQube token'ınızı buraya ekleyin
        run: |
          # SonarQube analizini sonar-project.properties dosyasından yapılandırarak başlat
          sonar-scanner -Dproject.settings=sonar-project.properties
