name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - '**' # Bu, tüm branch'lerdeki push işlemlerini tetikler
  pull_request:
    branches:
      - main
      - '**' # Bu, tüm branch'ler için PR oluşturulduğunda tetikler

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache SonarQube dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-cache
        restore-keys: ${{ runner.os }}-sonar-cache

    - name: Run SonarQube scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my_project_key \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://your_sonarqube_server_url \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
