name: SonarQube Analysis

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
<<<<<<< HEAD
    branches:
      - main
      - '**' # Tüm branch'ler için PR oluşturulduğunda tetikledflflgfr
=======
    types: [opened, synchronize, reopened, closed]
>>>>>>> aa3687b43bf8d8465fb4cc247ecbc6d7abe5ed10

jobs:
  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
