name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Ana dalınıza göre ayarlayın
  pull_request:
    branches:
      - main  # Ana dalınıza göre ayarlayın

jobs:
  sonarqube_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Projede kullanılan Node.js sürümüne göre ayarlayın

      - name: Install dependencies
        run: npm install  # Projeye bağlı olarak gerekirse değiştirilebilir

      - name: SonarQube Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SonarQube token'ınızı buraya ekleyin
        run: |
          sonar-scanner \
            -Dsonar.projectKey=SonarQube-Node.js \
            -Dsonar.organization=your_organization_key \
            -Dsonar.sources=. \
            -Dsonar.language=js \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.exclusions='**/node_modules/**,**/*.spec.js' \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
